language: objective-c
osx_image: xcode9.2
cache:
    - cocoapods
    - bundler

before_install:

- git submodule sync
- git submodule update --init --recursive
#- rvm install 2.2.4
- gem install cocoapods
- gem install xcpretty

- pod --version
- pod setup --silent
- pod repo update --silent

#check podspec
#- travis_wait 35 pod spec lint --use-libraries --allow-warnings ShareKit.podspec

#check podspec with current commit
- pod lib lint --use-libraries --allow-warnings ShareKit.podspec --no-subspecs

script:

#build library
- xcodebuild -project "ShareKit.xcodeproj" -scheme "Static Library" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty && exit ${PIPESTATUS[0]}

#run tests
- xcodebuild test -project "ShareKit.xcodeproj" -scheme "Static Library" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone SE,OS=latest'| xcpretty && exit ${PIPESTATUS[0]}
